//! Lets Iranian sites bypass the tunnel instead of going through it.
//!
//! Filtering only applies to traffic that looks like it left Iran, so a site
//! that is already reachable directly gains nothing from the tunnel and loses
//! the exit's bandwidth. Without this, seeing those sites at ordinary speed
//! means disconnecting -- which is the exact friction users asked to be rid
//! of.
//!
//! The two lists this reads are compiled into the binary with
//! [`include_str!`], not fetched at runtime: fetching them needs a working
//! connection to GitHub, which is exactly what a filtered network does not
//! have before the tunnel is up -- the same chicken-and-egg problem `GEOIP`'s
//! MMDB download has, which is why that option was rejected earlier. A
//! snapshot ships with the app instead, refreshed by hand with
//! `scripts/update-iran-routes.mjs` before a release.

use std::io::Write;
use std::path::Path;

/// Community-maintained, GPL-3.0, refreshed daily upstream:
/// <https://github.com/Chocolate4U/Iran-clash-rules>. See
/// THIRD_PARTY_NOTICES.md for the licence.
const IRAN_IP_RANGES: &str = include_str!("../../routing/iran-ip-ranges.txt");
const IRAN_DOMAINS: &str = include_str!("../../routing/iran-domains.txt");

/// The raw IP-CIDR list, mihomo's own format: one range per line, `#`
/// comments allowed. Handed to mihomo unmodified as an `ipcidr` rule-provider.
pub fn ip_ranges_for_mihomo() -> &'static str {
    IRAN_IP_RANGES
}

/// The raw domain list, mihomo's own format: `+.example.com` per line. Handed
/// to mihomo unmodified as a `domain` rule-provider.
pub fn domains_for_mihomo() -> &'static str {
    IRAN_DOMAINS
}

/// The domain list in Aether's `--routes` format.
///
/// The two engines write the same idea differently: mihomo's `+.` prefix
/// means "this name and every subdomain", which is what a bare line already
/// means to Aether's parser (`normalize_domain` strips a leading `*` and `.`
/// but not `+`, so an unstripped `+.example.com` line would be read as a
/// literal, broken domain rather than as a suffix rule).
fn domains_for_aether() -> String {
    IRAN_DOMAINS
        .lines()
        .map(|line| line.trim())
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| line.strip_prefix("+.").unwrap_or(line))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Writes a `--routes` file Aether can load: the bundled Iran list under
/// `[direct]`, plus whatever the user already had in their own routes file
/// (both its `[block]` and `[direct]` sections, preserved).
///
/// Aether reads exactly one `--routes` path, so turning this on cannot simply
/// add a second file alongside the user's own -- the two have to become one.
/// Generated fresh on every write rather than edited in place, so a routes
/// file the user later points elsewhere is never confused with ours.
pub fn write_combined_routes_file(
    destination: &Path,
    user_routes_file: Option<&Path>,
) -> Result<(), String> {
    let (user_block, user_direct) = match user_routes_file {
        Some(path) => {
            let text = std::fs::read_to_string(path).map_err(|error| {
                format!("cannot read the routes file {}: {error}", path.display())
            })?;
            split_sections(&text)
        }
        None => (String::new(), String::new()),
    };

    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("cannot prepare the routing directory: {error}"))?;
    }
    let mut file = std::fs::File::create(destination)
        .map_err(|error| format!("cannot write {}: {error}", destination.display()))?;

    writeln!(file, "# Generated by WhiteAesther. Edited by hand, this is overwritten on the")
        .and_then(|()| writeln!(file, "# next connect -- change the routes file in Advanced instead."))
        .and_then(|()| writeln!(file, "[block]"))
        .and_then(|()| write!(file, "{user_block}"))
        .and_then(|()| writeln!(file, "[direct]"))
        .and_then(|()| writeln!(file, "{}", domains_for_aether()))
        .and_then(|()| write!(file, "{IRAN_IP_RANGES}"))
        .and_then(|()| write!(file, "{user_direct}"))
        .map_err(|error| format!("cannot write {}: {error}", destination.display()))
}

/// The same section split Aether's own parser does: everything before the
/// first recognised `[block]`/`[direct]` header is dropped, and an
/// unrecognised header (`[proxy]`, a typo) resets the current section rather
/// than being folded into whichever one came before it. Reimplemented rather
/// than shared, because it belongs to a different crate; kept in step with
/// `aether::routing::split_sections` by the tests below.
fn split_sections(text: &str) -> (String, String) {
    let mut block = String::new();
    let mut direct = String::new();
    let mut current: Option<&mut String> = None;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let lowered = trimmed.to_lowercase();
        if lowered == "[block]" {
            current = Some(&mut block);
            continue;
        }
        if lowered == "[direct]" {
            current = Some(&mut direct);
            continue;
        }
        if lowered.starts_with('[') {
            current = None;
            continue;
        }
        if let Some(target) = current.as_deref_mut() {
            target.push_str(trimmed);
            target.push('\n');
        }
    }
    (block, direct)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_bundled_lists_are_not_empty() {
        // A build that shipped with an accidentally-truncated file would still
        // compile; only a real check catches it.
        assert!(IRAN_IP_RANGES.lines().filter(|l| !l.starts_with('#')).count() > 1000);
        assert!(IRAN_DOMAINS.lines().filter(|l| !l.starts_with('#')).count() > 10_000);
    }

    #[test]
    fn every_ip_line_is_a_cidr_or_a_comment() {
        for line in IRAN_IP_RANGES.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (address, prefix) = line.split_once('/').unwrap_or_else(|| panic!("not a CIDR: {line}"));
            address
                .parse::<std::net::IpAddr>()
                .unwrap_or_else(|_| panic!("not an address: {line}"));
            let prefix: u8 = prefix.parse().unwrap_or_else(|_| panic!("not a prefix length: {line}"));
            assert!(prefix <= 128, "prefix out of range: {line}");
        }
    }

    #[test]
    fn every_domain_line_uses_the_mihomo_suffix_prefix() {
        for line in IRAN_DOMAINS.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            assert!(line.starts_with("+."), "expected mihomo's +. prefix: {line}");
        }
    }

    #[test]
    fn aether_gets_the_same_names_without_mihomo_s_prefix() {
        let transformed = domains_for_aether();
        assert!(!transformed.contains("+."), "Aether reads a leading + as a literal character");
        assert!(transformed.lines().count() > 10_000);
        // A name from the source list survives, unprefixed.
        let sample = IRAN_DOMAINS
            .lines()
            .map(str::trim)
            .find(|l| l.starts_with("+."))
            .unwrap()
            .trim_start_matches("+.");
        assert!(transformed.lines().any(|l| l == sample), "{sample} missing from: {transformed}");
    }

    #[test]
    fn a_users_own_routes_survive_being_combined_with_the_bundled_list() {
        let dir = std::env::temp_dir().join(format!("whiteaesther-iran-routes-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let user_file = dir.join("mine.txt");
        std::fs::write(&user_file, "[block]\nads.example\n\n[direct]\nmy-own-site.example\n10.0.0.0/8\n").unwrap();

        let out = dir.join("combined.txt");
        write_combined_routes_file(&out, Some(&user_file)).unwrap();
        let combined = std::fs::read_to_string(&out).unwrap();

        assert!(combined.contains("ads.example"), "the user's block rule must survive");
        assert!(combined.contains("my-own-site.example"), "the user's direct rule must survive");
        assert!(combined.contains("10.0.0.0/8"), "the user's direct rule must survive");
        assert!(combined.contains("2.144.0.0/14"), "the bundled Iran ranges must be present");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn no_custom_file_still_produces_a_usable_routes_file() {
        let dir = std::env::temp_dir().join(format!("whiteaesther-iran-routes-test2-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("combined.txt");
        write_combined_routes_file(&out, None).unwrap();
        let combined = std::fs::read_to_string(&out).unwrap();
        assert!(combined.contains("[direct]"));
        assert!(combined.contains("2.144.0.0/14"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_unrecognised_header_does_not_leak_into_the_previous_section() {
        // Matches aether::routing::split_sections exactly: a stray heading
        // resets the current section instead of folding into it, so a typo in
        // a user's file fails closed (rules dropped) rather than open (rules
        // silently misfiled as direct or block).
        let (block, direct) = split_sections("[block]\nads.example\n[proxy]\nshould-vanish.example\n[direct]\nfine.example\n");
        assert_eq!(block, "ads.example\n");
        assert_eq!(direct, "fine.example\n");
    }
}
